-- create database "country-geo" with owner postgres;

create extension if not exists "uuid-ossp";

create table if not exists countries
(
    id                      UUID    unique        not null default uuid_generate_v1(),
    country_name               varchar(255) unique not null,
    country_code                varchar(50) unique not null,
    primary key (id)
    );

alter table countries
    owner to postgres;

insert into countries(country_name, country_code)values ('Fiji', 'FJ');
insert into countries(country_name, country_code)values ('Tanzania', 'TZ');
insert into countries(country_name, country_code)values ('Western Sahara', 'EH');
insert into countries(country_name, country_code)values ('Canada', 'CA');
insert into countries(country_name, country_code)values ('United States', 'US');
insert into countries(country_name, country_code)values ('Kazakhstan', 'KZ');
insert into countries(country_name, country_code)values ('Uzbekistan', 'UZ');
insert into countries(country_name, country_code)values ('Papua New Guinea', 'PG');
insert into countries(country_name, country_code)values ('Indonesia', 'ID');
insert into countries(country_name, country_code)values ('Argentina', 'AR');
insert into countries(country_name, country_code)values ('Chile', 'CL');
insert into countries(country_name, country_code)values ('Democratic Republic of the Congo', 'CD');
insert into countries(country_name, country_code)values ('Somalia', 'SO');
insert into countries(country_name, country_code)values ('Kenya', 'KE');
insert into countries(country_name, country_code)values ('Sudan', 'SD');
insert into countries(country_name, country_code)values ('Chad', 'TD');
insert into countries(country_name, country_code)values ('Haiti', 'HT');
insert into countries(country_name, country_code)values ('Dominican Republic', 'DO');
insert into countries(country_name, country_code)values ('Russia', 'RU');
insert into countries(country_name, country_code)values ('Bahamas', 'BS');
insert into countries(country_name, country_code)values ('Falkland Islands', 'FK');
insert into countries(country_name, country_code)values ('Norway', 'NO');
insert into countries(country_name, country_code)values ('Greenland', 'GL');
insert into countries(country_name, country_code)values ('Timor-Leste', 'TL');
insert into countries(country_name, country_code)values ('South Africa', 'ZA');
insert into countries(country_name, country_code)values ('Lesotho', 'LS');
insert into countries(country_name, country_code)values ('Mexico', 'MX');
insert into countries(country_name, country_code)values ('Uruguay', 'UY');
insert into countries(country_name, country_code)values ('Brazil', 'BR');
insert into countries(country_name, country_code)values ('Bolivia', 'BO');
insert into countries(country_name, country_code)values ('Peru', 'PE');
insert into countries(country_name, country_code)values ('Colombia', 'CO');
insert into countries(country_name, country_code)values ('Panama', 'PA');
insert into countries(country_name, country_code)values ('Costa Rica', 'CR');
insert into countries(country_name, country_code)values ('Nicaragua', 'NI');
insert into countries(country_name, country_code)values ('Honduras', 'HN');
insert into countries(country_name, country_code)values ('El Salvador', 'SV');
insert into countries(country_name, country_code)values ('Guatemala', 'GT');
insert into countries(country_name, country_code)values ('Belize', 'BZ');
insert into countries(country_name, country_code)values ('Venezuela', 'VE');
insert into countries(country_name, country_code)values ('Guyana', 'GY');
insert into countries(country_name, country_code)values ('Suriname', 'SR');
insert into countries(country_name, country_code)values ('France', 'FR');
insert into countries(country_name, country_code)values ('Ecuador', 'EC');
insert into countries(country_name, country_code)values ('Puerto Rico', 'PR');
insert into countries(country_name, country_code)values ('Jamaica', 'JM');
insert into countries(country_name, country_code)values ('Cuba', 'CU');
insert into countries(country_name, country_code)values ('Zimbabwe', 'ZW');
insert into countries(country_name, country_code)values ('Botswana', 'BW');
insert into countries(country_name, country_code)values ('Namibia', 'NA');
insert into countries(country_name, country_code)values ('Senegal', 'SN');
insert into countries(country_name, country_code)values ('Mali', 'ML');
insert into countries(country_name, country_code)values ('Mauritania', 'MR');
insert into countries(country_name, country_code)values ('Benin', 'BJ');
insert into countries(country_name, country_code)values ('Niger', 'NE');
insert into countries(country_name, country_code)values ('Nigeria', 'NG');
insert into countries(country_name, country_code)values ('Cameroon', 'CM');
insert into countries(country_name, country_code)values ('Togo', 'TG');
insert into countries(country_name, country_code)values ('Ghana', 'GH');
insert into countries(country_name, country_code)values ('Côted''Ivoire', 'CI');
insert into countries(country_name, country_code)values ('Guinea', 'GN');
insert into countries(country_name, country_code)values ('Guinea-Bissau', 'GW');
insert into countries(country_name, country_code)values ('Liberia', 'LR');
insert into countries(country_name, country_code)values ('Sierra Leone', 'SL');
insert into countries(country_name, country_code)values ('Burkina Faso', 'BF');
insert into countries(country_name, country_code)values ('Central African Republic', 'CF');
insert into countries(country_name, country_code)values ('Republic of the Congo', 'CG');
insert into countries(country_name, country_code)values ('Gabon', 'GA');
insert into countries(country_name, country_code)values ('Equatorial Guinea', 'GQ');
insert into countries(country_name, country_code)values ('Zambia', 'ZM');
insert into countries(country_name, country_code)values ('Malawi', 'MW');
insert into countries(country_name, country_code)values ('Mozambique', 'MZ');
insert into countries(country_name, country_code)values ('Eswatini', 'SZ');
insert into countries(country_name, country_code)values ('Angola', 'AO');
insert into countries(country_name, country_code)values ('Burundi', 'BI');
insert into countries(country_name, country_code)values ('Israel', 'IL');
insert into countries(country_name, country_code)values ('Lebanon', 'LB');
insert into countries(country_name, country_code)values ('Madagascar', 'MG');
insert into countries(country_name, country_code)values ('Palestine', 'PS');
insert into countries(country_name, country_code)values ('The Gambia', 'GM');
insert into countries(country_name, country_code)values ('Tunisia', 'TN');
insert into countries(country_name, country_code)values ('Algeria', 'DZ');
insert into countries(country_name, country_code)values ('Jordan', 'JO');
insert into countries(country_name, country_code)values ('United Arab Emirates', 'AE');
insert into countries(country_name, country_code)values ('Qatar', 'QA');
insert into countries(country_name, country_code)values ('Kuwait', 'KW');
insert into countries(country_name, country_code)values ('Iraq', 'IQ');
insert into countries(country_name, country_code)values ('Oman', 'OM');
insert into countries(country_name, country_code)values ('Vanuatu', 'VU');
insert into countries(country_name, country_code)values ('Cambodia', 'KH');
insert into countries(country_name, country_code)values ('Thailand', 'TH');
insert into countries(country_name, country_code)values ('Lao PDR', 'LA');
insert into countries(country_name, country_code)values ('Myanmar', 'MM');
insert into countries(country_name, country_code)values ('Vietnam', 'VN');
insert into countries(country_name, country_code)values ('Dem. Rep. Korea', 'KP');
insert into countries(country_name, country_code)values ('Republic of Korea', 'KR');
insert into countries(country_name, country_code)values ('Mongolia', 'MN');
insert into countries(country_name, country_code)values ('India', 'IN');
insert into countries(country_name, country_code)values ('Bangladesh', 'BD');
insert into countries(country_name, country_code)values ('Bhutan', 'BT');
insert into countries(country_name, country_code)values ('Nepal', 'NP');
insert into countries(country_name, country_code)values ('Pakistan', 'PK');
insert into countries(country_name, country_code)values ('Afghanistan', 'AF');
insert into countries(country_name, country_code)values ('Tajikistan', 'TJ');
insert into countries(country_name, country_code)values ('Kyrgyzstan', 'KG');
insert into countries(country_name, country_code)values ('Turkmenistan', 'TM');
insert into countries(country_name, country_code)values ('Iran', 'IR');
insert into countries(country_name, country_code)values ('Syria', 'SY');
insert into countries(country_name, country_code)values ('Armenia', 'AM');
insert into countries(country_name, country_code)values ('Sweden', 'SE');
insert into countries(country_name, country_code)values ('Belarus', 'BY');
insert into countries(country_name, country_code)values ('Ukraine', 'UA');
insert into countries(country_name, country_code)values ('Poland', 'PL');
insert into countries(country_name, country_code)values ('Austria', 'AT');
insert into countries(country_name, country_code)values ('Hungary', 'HU');
insert into countries(country_name, country_code)values ('Moldova', 'MD');
insert into countries(country_name, country_code)values ('Romania', 'RO');
insert into countries(country_name, country_code)values ('Lithuania', 'LT');
insert into countries(country_name, country_code)values ('Latvia', 'LV');
insert into countries(country_name, country_code)values ('Estonia', 'EE');
insert into countries(country_name, country_code)values ('Germany', 'DE');
insert into countries(country_name, country_code)values ('Bulgaria', 'BG');
insert into countries(country_name, country_code)values ('Greece', 'GR');
insert into countries(country_name, country_code)values ('Turkey', 'TR');
insert into countries(country_name, country_code)values ('Albania', 'AL');
insert into countries(country_name, country_code)values ('Croatia', 'HR');
insert into countries(country_name, country_code)values ('Switzerland', 'CH');
insert into countries(country_name, country_code)values ('Luxembourg', 'LU');
insert into countries(country_name, country_code)values ('Belgium', 'BE');
insert into countries(country_name, country_code)values ('Netherlands', 'NL');
insert into countries(country_name, country_code)values ('Portugal', 'PT');
insert into countries(country_name, country_code)values ('Spain', 'ES');
insert into countries(country_name, country_code)values ('Ireland', 'IE');
insert into countries(country_name, country_code)values ('New Caledonia', 'NC');
insert into countries(country_name, country_code)values ('Solomon Islands', 'SB');
insert into countries(country_name, country_code)values ('New Zealand', 'NZ');
insert into countries(country_name, country_code)values ('Australia', 'AU');
insert into countries(country_name, country_code)values ('Sri Lanka', 'LK');
insert into countries(country_name, country_code)values ('China', 'CN');
insert into countries(country_name, country_code)values ('Taiwan', 'TW');
insert into countries(country_name, country_code)values ('Italy', 'IT');
insert into countries(country_name, country_code)values ('Denmark', 'DK');
insert into countries(country_name, country_code)values ('United Kingdom', 'GB');
insert into countries(country_name, country_code)values ('Iceland', 'IS');
insert into countries(country_name, country_code)values ('Azerbaijan', 'AZ');
insert into countries(country_name, country_code)values ('Georgia', 'GE');
insert into countries(country_name, country_code)values ('Philippines', 'PH');
insert into countries(country_name, country_code)values ('Malaysia', 'MY');
insert into countries(country_name, country_code)values ('Brunei Darussalam', 'BN');
insert into countries(country_name, country_code)values ('Slovenia', 'SI');
insert into countries(country_name, country_code)values ('Finland', 'FI');
insert into countries(country_name, country_code)values ('Slovakia', 'SK');
insert into countries(country_name, country_code)values ('Czech Republic', 'CZ');
insert into countries(country_name, country_code)values ('Eritrea', 'ER');
insert into countries(country_name, country_code)values ('Japan', 'JP');
insert into countries(country_name, country_code)values ('Paraguay', 'PY');
insert into countries(country_name, country_code)values ('Yemen', 'YE');
insert into countries(country_name, country_code)values ('Saudi Arabia', 'SA');
insert into countries(country_name, country_code)values ('Northern Cyprus', 'CYP');
insert into countries(country_name, country_code)values ('Cyprus', 'CY');
insert into countries(country_name, country_code)values ('Morocco', 'MA');
insert into countries(country_name, country_code)values ('Egypt', 'EG');
insert into countries(country_name, country_code)values ('Libya', 'LY');
insert into countries(country_name, country_code)values ('Ethiopia', 'ET');
insert into countries(country_name, country_code)values ('Djibouti', 'DJ');
insert into countries(country_name, country_code)values ('Somaliland', 'SOM');
insert into countries(country_name, country_code)values ('Uganda', 'UG');
insert into countries(country_name, country_code)values ('Rwanda', 'RW');
insert into countries(country_name, country_code)values ('Bosnia and Herzegovina', 'BA');
insert into countries(country_name, country_code)values ('Macedonia', 'MK');
insert into countries(country_name, country_code)values ('Serbia', 'RS');
insert into countries(country_name, country_code)values ('Montenegro', 'ME');
insert into countries(country_name, country_code)values ('Kosovo', 'XK');
insert into countries(country_name, country_code)values ('Trinidad and Tobago', 'TT');
insert into countries(country_name, country_code)values ('South Sudan', 'SS');